// Send a 6-digit OTP code to a user's email via Resend.
// The OTP itself is generated by the client and posted here only for delivery.

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const FROM_ADDRESS =
  Deno.env.get("RESEND_FROM_ADDRESS") ?? "Collinz <onboarding@resend.dev>";

function escapeHtml(input: string): string {
  return input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function buildEmail(otp: string, ttlSeconds: number) {
  const safeOtp = escapeHtml(otp);
  const minutes = Math.max(1, Math.round(ttlSeconds / 60));
  const ttlLabel =
    ttlSeconds < 60
      ? `${ttlSeconds} seconds`
      : `${minutes} minute${minutes === 1 ? "" : "s"}`;

  const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Your one-time login code</title>
  </head>
  <body style="margin:0;padding:0;background:#f4f6f8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#1f2933;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#f4f6f8;padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="max-width:480px;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 6px 24px rgba(15,23,42,0.06);">
            <tr>
              <td style="padding:32px 32px 0 32px;">
                <h1 style="margin:0 0 8px 0;font-size:20px;font-weight:600;color:#0f172a;">Your login code</h1>
                <p style="margin:0;font-size:14px;line-height:20px;color:#475569;">
                  Use the one-time code below to finish signing in. It expires in ${ttlLabel}.
                </p>
              </td>
            </tr>
            <tr>
              <td align="center" style="padding:24px 32px;">
                <div style="display:inline-block;padding:18px 28px;background:#f1f5f9;border:1px solid #e2e8f0;border-radius:12px;font-family:'SFMono-Regular',Menlo,Consolas,monospace;font-size:32px;letter-spacing:10px;font-weight:700;color:#0f172a;">
                  ${safeOtp}
                </div>
              </td>
            </tr>
            <tr>
              <td style="padding:0 32px 32px 32px;">
                <p style="margin:0 0 12px 0;font-size:13px;line-height:20px;color:#475569;">
                  If you didn't request this code, you can safely ignore this email — no changes will be made to your account.
                </p>
                <p style="margin:0;font-size:12px;line-height:18px;color:#94a3b8;">
                  Sent by Collinz · Please do not reply to this email.
                </p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;

  const text = `Your one-time login code is ${otp}.
It expires in ${ttlLabel}.

If you didn't request this code, you can ignore this email.`;

  return { html, text };
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
    if (!RESEND_API_KEY) {
      return new Response(
        JSON.stringify({ error: "RESEND_API_KEY is not configured" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    const body = await req.json().catch(() => ({}));
    const email = String(body?.email ?? "").trim().toLowerCase();
    const otp = String(body?.otp ?? "").trim();
    const ttlSeconds = Number.isFinite(body?.ttl_seconds)
      ? Number(body.ttl_seconds)
      : 60;

    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return new Response(
        JSON.stringify({ error: "A valid email is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }
    if (!/^\d{4,8}$/.test(otp)) {
      return new Response(
        JSON.stringify({ error: "A numeric OTP code is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    const { html, text } = buildEmail(otp, ttlSeconds);

    const resendRes = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: FROM_ADDRESS,
        to: [email],
        subject: `Your login code: ${otp}`,
        html,
        text,
      }),
    });

    const resendBody = await resendRes.json().catch(() => ({}));

    if (!resendRes.ok) {
      console.error("[send-email-otp] Resend error", resendRes.status, resendBody);
      return new Response(
        JSON.stringify({
          error:
            (resendBody as any)?.message ??
            `Resend request failed (${resendRes.status})`,
        }),
        { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    return new Response(
      JSON.stringify({ success: true, id: (resendBody as any)?.id ?? null }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  } catch (err) {
    console.error("[send-email-otp] unexpected error", err);
    return new Response(
      JSON.stringify({ error: err instanceof Error ? err.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }
});