// Send a 6-digit OTP code to a user's email via Resend.
// The OTP itself is generated by the client and posted here only for delivery.

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const FROM_ADDRESS =
  Deno.env.get("RESEND_FROM_ADDRESS") ?? "Collinz <onboarding@resend.dev>";

function escapeHtml(input: string): string {
  return input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function buildEmail(otp: string, ttlSeconds: number) {
  const safeOtp = escapeHtml(otp);
  const minutes = Math.max(1, Math.round(ttlSeconds / 60));
  const ttlLabel =
    ttlSeconds < 60
      ? `${ttlSeconds} seconds`
      : `${minutes} minute${minutes === 1 ? "" : "s"}`;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Your Collinz OTP Code</title>
</head>
<body style="margin: 0; padding: 0; background-color: #f4f6f8; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;">

  <!-- Wrapper -->
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background-color: #f4f6f8; padding: 40px 20px;">
    <tr>
      <td align="center">

        <!-- Main card -->
        <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="max-width: 480px; background-color: #ffffff; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.04); overflow: hidden;">

          <!-- Header -->
          <tr>
            <td style="background-color: #1e3a5f; padding: 28px 32px; text-align: center;">
              <h1 style="margin: 0; color: #ffffff; font-size: 22px; font-weight: 600; letter-spacing: 0.3px;">
                Collinz School Management
              </h1>
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding: 36px 32px 24px 32px; color: #2c3e50;">
              <p style="margin: 0 0 16px 0; font-size: 16px; line-height: 1.5;">
                Hello,
              </p>
              <p style="margin: 0 0 28px 0; font-size: 15px; line-height: 1.6; color: #4a5568;">
                Your one-time password (OTP) for the Collinz School Management App is:
              </p>

              <!-- OTP box -->
              <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0">
                <tr>
                  <td align="center" style="background-color: #f0f4f8; border: 1px dashed #cbd5e0; border-radius: 8px; padding: 20px;">
                    <span style="font-family: 'Courier New', Courier, monospace; font-size: 32px; font-weight: 700; color: #1e3a5f; letter-spacing: 8px;">
                      ${safeOtp}
                    </span>
                  </td>
                </tr>
              </table>

              <p style="margin: 28px 0 0 0; font-size: 14px; line-height: 1.6; color: #4a5568;">
                Please enter this code to continue. This code is valid for ${ttlLabel}.
              </p>

              <p style="margin: 16px 0 0 0; font-size: 14px; line-height: 1.6; color: #718096;">
                If you're unsure or did not request this, kindly contact the school admin.
              </p>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="background-color: #fafbfc; padding: 20px 32px; text-align: center; border-top: 1px solid #edf2f7;">
              <p style="margin: 0; font-size: 12px; color: #a0aec0; line-height: 1.5;">
                This is an automated message from Collinz School Management.<br>
                Please do not reply to this email.
              </p>
            </td>
          </tr>

        </table>

        <!-- Bottom spacer / brand -->
        <p style="margin: 20px 0 0 0; font-size: 12px; color: #a0aec0;">
          &copy; Collinz Education Group
        </p>

      </td>
    </tr>
  </table>

</body>
</html>`;

  const text = `Your Collinz OTP code is ${otp}.
This code is valid for ${ttlLabel}.

If you did not request this, please contact the school admin.`;

  return { html, text };
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
    if (!RESEND_API_KEY) {
      return new Response(
        JSON.stringify({ error: "RESEND_API_KEY is not configured" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    const body = await req.json().catch(() => ({}));
    const email = String(body?.email ?? "").trim().toLowerCase();
    const otp = String(body?.otp ?? "").trim();
    const ttlSeconds = Number.isFinite(body?.ttl_seconds)
      ? Number(body.ttl_seconds)
      : 60;

    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return new Response(
        JSON.stringify({ error: "A valid email is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }
    if (!/^\d{4,8}$/.test(otp)) {
      return new Response(
        JSON.stringify({ error: "A numeric OTP code is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    const { html, text } = buildEmail(otp, ttlSeconds);

    const resendRes = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: FROM_ADDRESS,
        to: [email],
        subject: `Your login code: ${otp}`,
        html,
        text,
      }),
    });

    const resendBody = await resendRes.json().catch(() => ({}));

    if (!resendRes.ok) {
      console.error("[send-email-otp] Resend error", resendRes.status, resendBody);
      return new Response(
        JSON.stringify({
          error:
            (resendBody as any)?.message ??
            `Resend request failed (${resendRes.status})`,
        }),
        { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    return new Response(
      JSON.stringify({ success: true, id: (resendBody as any)?.id ?? null }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  } catch (err) {
    console.error("[send-email-otp] unexpected error", err);
    return new Response(
      JSON.stringify({ error: err instanceof Error ? err.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }
});